publish_mode: editorial_workflow
backend:
  name: github
  repo: oogimishakyo/oogimishakyo.github.io
  branch: main
  base_url: https://oogimishakyo-cms-auth2.yuzi-5eb.workers.dev
  auth_endpoint: auth
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "news"
    label: "お知らせ"
    folder: "data/news"
    create: true
    extension: json
    format: json
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "日付", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "カテゴリ", name: "category", widget: "select", options: ["お知らせ", "事業案内", "催し"] }
      - { label: "本文", name: "body", widget: "text" }
      - { label: "URL（任意）", name: "url", widget: "string", required: false }
      - { label: "添付PDF（任意）", name: "pdf", widget: "file", required: false }
